In [ ]:
# Good evening sir,my name is kshitij singhania CCE 'B' 23FE10CCE00152
# this is my 2nd foundation of data science assignment

# I have provided comment for each step to make it easy for other to understand 

#⁠ Q1. Write Python code for addition, subtraction, multiplication, element-wise 
# multiplication, determinant,the inverse of the matrix using NumPy and SciPy package.

# Import necessary libraries
import numpy as np
from scipy.linalg import det, inv  # Import determinant and inverse functions from SciPy

# Define two matrices as examples
# Matrix A
A = np.array([[1, 2], [3, 4]])
# Matrix B
B = np.array([[5, 6], [7, 8]])

# Display the matrices
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# 1. Matrix Addition
# Add corresponding elements of A and B
addition = A + B
print("\n1. Matrix Addition (A + B):")
print(addition)

# 2. Matrix Subtraction
# Subtract corresponding elements of B from A
subtraction = A - B
print("\n2. Matrix Subtraction (A - B):")
print(subtraction)

# 3. Matrix Multiplication
# Perform matrix multiplication (dot product)
multiplication = np.dot(A, B)
print("\n3. Matrix Multiplication (A * B):")
print(multiplication)

# 4. Element-wise Multiplication
# Multiply corresponding elements of A and B
element_wise_multiplication = A * B
print("\n4. Element-wise Multiplication (A .* B):")
print(element_wise_multiplication)

# 5. Determinant of a Matrix
# Calculate the determinant of matrix A
determinant_A = det(A)
print("\n5. Determinant of Matrix A:")
print(f"Determinant of A = {determinant_A}")

# 6. Inverse of a Matrix
# Calculate the inverse of matrix A
# A matrix must be square and non-singular (determinant != 0) to have an inverse

print("\n6. Inverse of Matrix A:")
if determinant_A != 0:
    inverse_A = inv(A)
    print("Inverse of A:")
    print(inverse_A)
else:
    print("Matrix A is singular and does not have an inverse.")






# Q2. Write Python code to calculate eigenvalue and eigenvector of a matrix.
# Check the orthogonality of the eigenvector.


# Import necessary libraries
import numpy as np

# Define a square matrix
# Example matrix
A = np.array([[4, -2],
              [1, 1]])

# Display the matrix
print("Matrix A:")
print(A)

# 1. Calculate Eigenvalues and Eigenvectors
# Use NumPy's `linalg.eig` function to compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display the eigenvalues
print("\n1. Eigenvalues of Matrix A:")
print(eigenvalues)

# Display the eigenvectors
print("\n2. Eigenvectors of Matrix A:")
print(eigenvectors)

# 2. Check Orthogonality of Eigenvectors
# Eigenvectors are orthogonal if their dot product is zero
# We will check the dot product of all pairs of eigenvectors

print("\n3. Checking Orthogonality of Eigenvectors:")

# Loop through all pairs of eigenvectors
for i in range(len(eigenvectors)):
    for j in range(i + 1, len(eigenvectors)):
        # Compute the dot product of eigenvector i and eigenvector j
        dot_product = np.dot(eigenvectors[:, i], eigenvectors[:, j])
        print(f"Dot product of eigenvector {i + 1} and eigenvector {j + 1}: {dot_product}")

        # Check if the dot product is close to zero
        if np.isclose(dot_product, 0):
            print(f"Eigenvector {i + 1} and Eigenvector {j + 1} are orthogonal.")
        else:
            print(f"Eigenvector {i + 1} and Eigenvector {j + 1} are NOT orthogonal.")






# Q3. Calculate span and basis of a vector space using Python.


# Import necessary libraries
import numpy as np

# Define a set of vectors
# Example: Vectors in a 3-dimensional space
vectors = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Display the vectors
print("Given Vectors:")
print(vectors)

# 1. Calculate the Basis of the Vector Space
# Use NumPy's `linalg.matrix_rank` to find the rank of the matrix formed by the vectors
# The rank of the matrix gives the number of linearly independent vectors 
rank = np.linalg.matrix_rank(vectors)

# Find the linearly independent vectors

# Use NumPy's `linalg.qr` to perform QR decomposition and extract the independent vectors
Q, R = np.linalg.qr(vectors.T)  
# Transpose the matrix to work with columns
basis = Q[:, :rank].T 
# Take the first 'rank' columns of Q and transpose back

# Display the basis
print("\n1. Basis of the Vector Space:")
print(basis)

# 2. Calculate the Span of the Vector Space
# The span of the vector space is the set of all linear combinations of the basis vectors
# We will demonstrate this by generating a few random linear combinations

print("\n2. Span of the Vector Space (Example Linear Combinations):")
coefficients = np.random.rand(5, rank)  # Generate random coefficients for 5 combinations
span_examples = np.dot(coefficients, basis)  # Compute linear combinations

# Display the examples of vectors in the span
for i, span_vector in enumerate(span_examples, start=1):
    print(f"Example {i}: {span_vector}")







Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

1. Matrix Addition (A + B):
[[ 6  8]
 [10 12]]

2. Matrix Subtraction (A - B):
[[-4 -4]
 [-4 -4]]

3. Matrix Multiplication (A * B):
[[19 22]
 [43 50]]

4. Element-wise Multiplication (A .* B):
[[ 5 12]
 [21 32]]

5. Determinant of Matrix A:
Determinant of A = -2.0

6. Inverse of Matrix A:
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Matrix A:
[[ 4 -2]
 [ 1  1]]

1. Eigenvalues of Matrix A:
[3. 2.]

2. Eigenvectors of Matrix A:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

3. Checking Orthogonality of Eigenvectors:
Dot product of eigenvector 1 and eigenvector 2: 0.9486832980505137
Eigenvector 1 and Eigenvector 2 are NOT orthogonal.
Given Vectors:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. Basis of the Vector Space:
[[-0.26726124 -0.53452248 -0.80178373]
 [ 0.87287156  0.21821789 -0.43643578]]

2. Span of the Vector Space (Example Linear Combinations):
Example 1: [ 0.59912734 -0.15856012 -0.91624759]
Example 2: [ 0.65058186 -0.01136816 -0.67331